# Generated by Django 2.1.2 on 2018-10-09 15:06

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            bases=(app.models.RepresentationFieldNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            bases=(app.models.RepresentationFieldNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='Цена')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Company', verbose_name='Предприятие')),
            ],
            bases=(app.models.RepresentationFieldNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            bases=(app.models.RepresentationFieldNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EnterpriseNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            bases=(app.models.RepresentationFieldNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Category', verbose_name='Категория')),
                ('company', models.ManyToManyField(through='app.CompanyProduct', to='app.Company', verbose_name='Предприятие')),
            ],
            bases=(app.models.RepresentationFieldNameMixin, models.Model),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Product', verbose_name='Услуга\\товар'),
        ),
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.ManyToManyField(to='app.District', verbose_name='Район города'),
        ),
        migrations.AddField(
            model_name='company',
            name='enterprise_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.EnterpriseNetwork', verbose_name='Сеть предприятий'),
        ),
    ]
