# Generated by Django 2.1.2 on 2018-10-09 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181009_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproduct',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to='app.Company', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='companyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to='app.Product', verbose_name='Услуга\\товар'),
        ),
    ]
