# Generated by Django 2.1.2 on 2018-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181009_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='product',
            field=models.ManyToManyField(related_name='company_products', through='app.CompanyProduct', to='app.Product', verbose_name='Предприятие'),
        ),
    ]
