# Generated by Django 2.1.2 on 2018-10-09 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181009_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='product',
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.ManyToManyField(through='app.CompanyProduct', to='app.Product', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='companyproduct',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Company', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='companyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Product', verbose_name='Услуга\\товар'),
        ),
    ]
